[project]
name = "advent2024"
version = "0.1.0"
description = "Advent of Code 2024 - Python solutions by Ryan Echols"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.1.3",
    "tqdm>=4.67.1",
]
